name: Docker Image CI

on:
  push:
    branches:
      - master  # only when pushing *to* master
  pull_request:
    branches:
      - master  # only when PR targets master (source branch can be anything)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build the Docker image
        run: docker build --platform=linux/arm64/v8 . --file Dockerfile --tag ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/collectorservice:latest

      - name: Save Docker image
        run: docker save ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/collectorservice:latest -o collectorservice.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: collectorservice
          path: collectorservice.tar
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: collectorservice
          path: .

      - name: Load Docker image
        run: docker load -i collectorservice.tar

      - name: Push Docker image to GHCR
        run: docker push ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/collectorservice:latest
